/**
 * Icons:
 * {@link https://icon-sets.iconify.design/ic/}
 */

export { default as Github } from './github.svg?react'
export * from './instruments'
export { default as LinkedIn } from './linkedin.svg?react'
export { default as Twitter } from './twitter.svg?react'
export { default as Sparkles } from '@material-icons/svg/svg/auto_awesome/round.svg?react'
export { default as Bolt } from '@material-icons/svg/svg/bolt/round.svg?react'
export { default as Chat } from '@material-icons/svg/svg/chat/round.svg?react'
export { default as Check } from '@material-icons/svg/svg/check/round.svg?react'
export { default as ArrowLeft } from '@material-icons/svg/svg/chevron_left/round.svg?react'
export { default as ArrowRight } from '@material-icons/svg/svg/chevron_right/round.svg?react'
export { default as Circle } from '@material-icons/svg/svg/circle/round.svg?react'
export { default as Close } from '@material-icons/svg/svg/close/round.svg?react'
export { default as Copy } from '@material-icons/svg/svg/content_copy/round.svg?react'
export { default as Download } from '@material-icons/svg/svg/download/round.svg?react'
export { default as FilePresent } from '@material-icons/svg/svg/file_present/round.svg?react'
export { default as Info } from '@material-icons/svg/svg/info/round.svg?react'
export { default as ArrowDown } from '@material-icons/svg/svg/keyboard_arrow_down/round.svg?react'
export { default as Link } from '@material-icons/svg/svg/link/round.svg?react'
export { default as Mail } from '@material-icons/svg/svg/mail/round.svg?react'
export { default as LinkExternal } from '@material-icons/svg/svg/open_in_new/round.svg?react'
export { default as Play } from '@material-icons/svg/svg/play_arrow/baseline.svg?react'
export { default as Replay } from '@material-icons/svg/svg/replay/round.svg?react'
export { default as AlertOctagon } from '@material-icons/svg/svg/report/round.svg?react'
export { default as AlertTriangle } from '@material-icons/svg/svg/report_problem/round.svg?react'
export { default as Social } from '@material-icons/svg/svg/rss_feed/round.svg?react'
export { default as Search } from '@material-icons/svg/svg/search/round.svg?react'
export { default as Settings } from '@material-icons/svg/svg/settings/round.svg?react'
export { default as Square } from '@material-icons/svg/svg/square/round.svg?react'
export { default as Back } from '@material-icons/svg/svg/subdirectory_arrow_left/round.svg?react'
export { default as Upload } from '@material-icons/svg/svg/upload_file/round.svg?react'
